image: java:17

stages:
  -build
  -deploy

cache:
  paths:
    - .gradle/wrapper

build-job-dev:
  stage: build
  script:
    - ./gradlew clean build
  artifacts:
    path:
      - build/libs/*SNAPSHOT.jar
    expire_in: 1 week
  only:
    - test

#deploy-job-dev:
#  stage: deploy
#  script:
#    -
#  only:
#    - test



build-job-prod:
  stage: build
  script: ./gradlew clean build
  artifacts:
    path:
      - build/libs/*SNAPSHOT.jar
    expire_in: 1 week
  only:
    - main

#deploy-job-prod:
#  stage: deploy
#  only:
#    - main